### PR TITLE
Add DANDI page, update workshops, adjust images

### PR DESCRIPTION
**Pull request by CBroz1**
Screen Shot 2022-08-25 at 11 15 38
Screen Shot 2022-08-25 at 11 15 29
Screen Shot 2022-08-25 at 11 09 48

### CODE REVIEW

**Comment by kushalbakshi** [comment]
I can't see the DANDI logo when I launch the website from my localhost. Maybe the DANDI image needs to be added to a static folder? I've attached a screenshot below
Missing DANDI SC

**Review by kushalbakshi — CHANGES_REQUESTED** [review]
The DANDI logo does not appear when I run from localhost. Perhaps the image file needs to be added to a static images folder? Here's a screenshot of what I see when I launch the site from my machine: 

Missing DANDI SC

**Comment by CBroz1** [comment]
To get it running locally, you would need to uncomment one link and comment out the other here:
```html
<p align="center">
  <img src="https://github.com/datajoint/datajoint-elements/blob/main/docs/img/dandi.png?raw=true" width="83" height="83">&nbsp;&nbsp;
  <!-- <img src="https://www.dandiarchive.org/handbook/img/dandi-logo-square_sw.png" width="83" height="83">&nbsp;&nbsp;   -->
  <img src="https://raw.githubusercontent.com/datajoint/datajoint.org/0a05cf5c2530a3595a13fc11f6abac64746d845d/static/images/elements-logo.png" width="300" height="83">
</p> 
```

Currently, the path to their file on dandiarchive.org is commented out. The link I'm proposing we use is where the new uploaded image will be once this is merged

**Review by kushalbakshi — APPROVED** [review]

**Comment by CBroz1** [comment]
@kushalbakshi Thanks for merging. You can check the progress of the build/deployment to live site via github actions. 
- [Script that runs](https://github.com/datajoint/datajoint-elements/blob/main/.github/workflows/development.yaml)
- [This particular case](https://github.com/datajoint/datajoint-elements/runs/8020643506?check_suite_focus=true)

**Pull request merged**
